/**
 * useH2Agent Hook
 *
 * Main hook for interacting with the H2 LangChain agent.
 * Handles SSE connection, message streaming, and state management.
 */

import { useCallback, useEffect, useRef } from "react";
import { useH2ChatStore } from "@/stores/useH2ChatStore";
import { SSEClient } from "@/lib/h2/sseClient";
import type { SSEEvent, MessageTuple } from "@/lib/h2/types";
import { useIdentity, getIdentitySnapshot } from "./useIdentity";

// ============================================================================
// Hook
// ============================================================================

export function useH2Agent() {
  const sseClientRef = useRef<SSEClient | null>(null);

  // Get wallet from identity (needed for signature requests)
  const { wallet } = useIdentity();

  // Store selectors
  const messages = useH2ChatStore((state) => state.messages);
  const quickMode = useH2ChatStore((state) => state.quickMode);
  const sessionData = useH2ChatStore((state) => state.sessionData);
  const allowedTokens = useH2ChatStore((state) => state.allowedTokens);
  const connectionState = useH2ChatStore((state) => state.connectionState);
  const isStreaming = useH2ChatStore((state) => state.isStreaming);

  // Store actions
  const addMessage = useH2ChatStore((state) => state.addMessage);
  const updateMessageContent = useH2ChatStore((state) => state.updateMessageContent);
  const setStreamingMessage = useH2ChatStore((state) => state.setStreamingMessage);
  const hideProgress = useH2ChatStore((state) => state.hideProgress);
  const startTool = useH2ChatStore((state) => state.startTool);
  const completeTool = useH2ChatStore((state) => state.completeTool);
  const errorTool = useH2ChatStore((state) => state.errorTool);
  const addToolStep = useH2ChatStore((state) => state.addToolStep);
  const setConnectionState = useH2ChatStore((state) => state.setConnectionState);
  const setIsStreaming = useH2ChatStore((state) => state.setIsStreaming);

  /**
   * Handle SSE events
   */
  const handleSSEEvent = useCallback(
    (event: SSEEvent) => {
      switch (event.type) {
        case "token": {
          // Token streaming - append to current assistant message
          const streamingId = useH2ChatStore.getState().streamingMessageId;
          if (streamingId) {
            // Get current messages from store (not stale closure)
            const currentMessages = useH2ChatStore.getState().messages;
            const currentMessage = currentMessages.find((msg) => msg.id === streamingId);
            if (currentMessage && 'content' in currentMessage) {
              updateMessageContent(streamingId, currentMessage.content + event.content);
            }
          } else {
            // Create new assistant message and get the store-generated ID
            addMessage({
              role: "assistant",
              content: event.content || "",
              isStreaming: true,
            });

            // Get the ID that was just generated by the store
            const newMessage = useH2ChatStore.getState().messages.at(-1);
            if (newMessage) {
              setStreamingMessage(newMessage.id);
            }
          }
          break;
        }

        case "progress": {
          // All progress goes to tree as nested steps - no bubble
          if (event.message) {
            let runningToolName = event.toolName;

            // Find currently running tool if not specified
            if (!runningToolName) {
              const activeTools = useH2ChatStore.getState().activeTools;
              activeTools.forEach((tool, name) => {
                if (tool.status === "running") {
                  runningToolName = name;
                }
              });
            }

            // Add as tree step if we have a running tool
            if (runningToolName) {
              addToolStep(runningToolName, event.message);
            }
          }
          break;
        }

        case "tool_start": {
          // Tool execution started
          if (event.toolName) {
            startTool(event.toolName);
          }
          break;
        }

        case "tool_end": {
          // Tool execution completed
          if (event.toolName) {
            completeTool(event.toolName, event.output);
          }
          hideProgress();
          break;
        }

        case "tool_error": {
          // Tool execution failed
          if (event.toolName && event.error) {
            errorTool(event.toolName, event.error);
          }
          hideProgress();
          break;
        }

        case "signature_request": {
          // Server needs delegation signature from client
          if (!event.signatureRequest) {
            console.error("[H2 Agent] Invalid signature request event");
            break;
          }

          const { requestId, typedDataJson, from } = event.signatureRequest;
          console.log(`[H2 Agent] Signature request received: ${requestId}`);

          // Sign with owner wallet asynchronously
          (async () => {
            try {
              // Get fresh wallet state (not from closure)
              // This prevents stale closure issue when wallet connects after component renders
              const currentWallet = getIdentitySnapshot().wallet;

              // Check if wallet is available
              if (!currentWallet) {
                console.error("[H2 Agent] No wallet available for signing");
                addMessage({
                  role: "system",
                  content: "Error: Wallet not connected. Please connect your wallet to sign delegations.",
                });
                return;
              }

              // Parse typed data
              const typedData = JSON.parse(typedDataJson);

              console.log("[H2 Agent] Signing delegation with owner wallet...");

              // Sign with owner wallet (Web3Auth)
              const signature = await currentWallet.walletClient.signTypedData({
                account: from as `0x${string}`,
                domain: typedData.domain,
                types: typedData.types,
                primaryType: typedData.primaryType,
                message: typedData.message,
              });

              console.log("[H2 Agent] Signature created, sending to server...");

              // Send signature to server
              const response = await fetch("/api/h2/sign-response", {
                method: "POST",
                headers: { "Content-Type": "application/json" },
                body: JSON.stringify({
                  requestId,
                  signature,
                }),
              });

              if (!response.ok) {
                throw new Error(`Failed to send signature: ${response.statusText}`);
              }

              console.log("[H2 Agent] Signature sent successfully");
            } catch (error) {
              console.error("[H2 Agent] Signature error:", error);
              addMessage({
                role: "system",
                content: `Error signing delegation: ${error instanceof Error ? error.message : "Unknown error"}`,
              });
            }
          })();

          break;
        }

        case "done": {
          // Stream complete
          setStreamingMessage(null);
          setIsStreaming(false);
          hideProgress();
          break;
        }

        case "error": {
          // Stream error
          console.error("SSE stream error:", event.error);
          setStreamingMessage(null);
          setIsStreaming(false);
          hideProgress();

          // Add error message to chat
          addMessage({
            role: "system",
            content: `Error: ${event.error || "An error occurred while processing your request."}`,
          });
          break;
        }
      }
    },
    [
      messages,
      addMessage,
      updateMessageContent,
      setStreamingMessage,
      hideProgress,
      startTool,
      completeTool,
      errorTool,
      addToolStep,
      setIsStreaming,
    ]
  );

  /**
   * Send message to agent
   */
  const sendMessage = useCallback(
    async (content: string) => {
      // Get user address from session - no fallback!
      const userAddress = sessionData?.delegator;

      if (!userAddress) {
        // No session data - user needs to connect wallet
        addMessage({
          role: "system",
          content: "Please connect your wallet to use H2 chat.",
        });
        return;
      }

      // Add user message to chat
      addMessage({
        role: "user",
        content,
      });

      // Build message history for agent (LangChain format: [role, content] tuples)
      // Filter out tool messages - they're UI-only, not part of conversation history
      const messageHistory: MessageTuple[] = [
        ...messages
          .filter((msg) => msg.role !== "tool")
          .map((msg) => [msg.role, (msg as { content: string }).content] as MessageTuple),
        ["user", content],
      ];

      // DEBUG: Log allowed tokens being sent to agent
      console.log("[H2 Agent] Sending message to agent:", {
        userMessage: content,
        allowedTokensCount: allowedTokens.length,
        allowedTokens: allowedTokens,
        quickMode,
      });

      // Set streaming state
      setIsStreaming(true);

      // Disconnect existing client if any
      if (sseClientRef.current) {
        sseClientRef.current.disconnect();
      }

      // Create new SSE client
      sseClientRef.current = new SSEClient({
        apiUrl: "/api/h2/chat",
        messages: messageHistory,
        userAddress,
        sessionData: sessionData || undefined,
        quickMode,
        allowedTokens,
        onEvent: handleSSEEvent,
        onError: (error) => {
          console.error("SSE connection error:", error);
          setIsStreaming(false);
          hideProgress();

          // Add error message to chat
          addMessage({
            role: "system",
            content: `Connection error: ${error.message}. Please try again.`,
          });
        },
        onConnectionStateChange: (state) => {
          setConnectionState(state);
        },
      });

      // Start connection
      try {
        await sseClientRef.current.connect();
      } catch (error) {
        console.error("Failed to connect to agent:", error);
        setIsStreaming(false);
        setConnectionState("error");
      }
    },
    [
      sessionData,
      messages,
      quickMode,
      allowedTokens,
      addMessage,
      setIsStreaming,
      handleSSEEvent,
      setConnectionState,
      hideProgress,
    ]
  );

  /**
   * Cleanup on unmount
   */
  useEffect(() => {
    return () => {
      if (sseClientRef.current) {
        sseClientRef.current.disconnect();
      }
    };
  }, []);

  return {
    // State
    messages,
    connectionState,
    isStreaming,
    quickMode,

    // Actions
    sendMessage,

    // Utility
    isConnected: connectionState === "connected",
    isDisconnected: connectionState === "disconnected",
    isReconnecting: connectionState === "reconnecting",
    hasError: connectionState === "error",
  };
}
