const env = {
  NEXT_PUBLIC_MONAD_CHAIN_ID: process.env.NEXT_PUBLIC_MONAD_CHAIN_ID,
  NEXT_PUBLIC_MONAD_BLOCK_EXPLORER_URL: process.env.NEXT_PUBLIC_MONAD_BLOCK_EXPLORER_URL,
  NEXT_PUBLIC_MONAD_RPC_URL: process.env.NEXT_PUBLIC_MONAD_RPC_URL,
  NEXT_PUBLIC_MONAD_EXECUTION_RPC_URL: process.env.NEXT_PUBLIC_MONAD_EXECUTION_RPC_URL,
  NEXT_PUBLIC_MONAD_ENVIO_READ_RPC_URL: process.env.NEXT_PUBLIC_MONAD_ENVIO_READ_RPC_URL,
  // Removed: NEXT_PUBLIC_MONAD_HYPERSYNC_URL (unused)
  // Removed: NEXT_PUBLIC_ENVIO_TOKEN_API (server-only secret)
  // Removed: NEXT_PUBLIC_PIMLICO_API_KEY (server-only secret)
  NEXT_PUBLIC_PIMLICO_CHAIN: process.env.NEXT_PUBLIC_PIMLICO_CHAIN,
  NEXT_PUBLIC_PIMLICO_BUNDLER_URL: process.env.NEXT_PUBLIC_PIMLICO_BUNDLER_URL,
  NEXT_PUBLIC_PIMLICO_PAYMASTER_URL: process.env.NEXT_PUBLIC_PIMLICO_PAYMASTER_URL,
  NEXT_PUBLIC_PIMLICO_SPONSORSHIP_POLICY_ID: process.env.NEXT_PUBLIC_PIMLICO_SPONSORSHIP_POLICY_ID,
  NEXT_PUBLIC_WEB3_AUTH_ID: process.env.NEXT_PUBLIC_WEB3_AUTH_ID,
  NEXT_PUBLIC_WEB3_AUTH_NETWORK: process.env.NEXT_PUBLIC_WEB3_AUTH_NETWORK,
  NEXT_PUBLIC_MONORAIL_PATHFINDER_URL: process.env.NEXT_PUBLIC_MONORAIL_PATHFINDER_URL,
  NEXT_PUBLIC_MONORAIL_DATA_API_URL: process.env.NEXT_PUBLIC_MONORAIL_DATA_API_URL,
  // Note: Monorail uses App ID only - no API key required
  NEXT_PUBLIC_MONORAIL_APP_ID: process.env.NEXT_PUBLIC_MONORAIL_APP_ID,
  NEXT_PUBLIC_MONORAIL_AGGREGATOR_ADDRESS: process.env.NEXT_PUBLIC_MONORAIL_AGGREGATOR_ADDRESS,
  NEXT_PUBLIC_MONAD_NATIVE_TOKEN_ADDRESS: process.env.NEXT_PUBLIC_MONAD_NATIVE_TOKEN_ADDRESS,
  NEXT_PUBLIC_MONAD_NATIVE_TOKEN_SYMBOL: process.env.NEXT_PUBLIC_MONAD_NATIVE_TOKEN_SYMBOL,
  NEXT_PUBLIC_MONAD_WRAPPED_TOKEN_SYMBOL: process.env.NEXT_PUBLIC_MONAD_WRAPPED_TOKEN_SYMBOL,
  NEXT_PUBLIC_MONAD_WMON_ADDRESS: process.env.NEXT_PUBLIC_MONAD_WMON_ADDRESS,
  NEXT_PUBLIC_APRIORI_ADDRESS: process.env.NEXT_PUBLIC_APRIORI_ADDRESS,
  NEXT_PUBLIC_PRAGMA_IDENTITY_PROVIDER: process.env.NEXT_PUBLIC_PRAGMA_IDENTITY_PROVIDER,
  // Removed: NEXT_PUBLIC_PRIVY_ID (unused)
  // Removed: NEXT_PUBLIC_PRIVY_SECRET (unused secret)
  // Removed: NEXT_PUBLIC_PRAGMA_ADMIN_TEST_PK (critical secret - server-only)
  // Removed: NEXT_PUBLIC_OPENAI_API_KEY (server-only secret)
  // Removed: NEXT_PUBLIC_PRAGMA_DISABLE_HYPERSYNC (unused)
  NEXT_PUBLIC_PRAGMA_AGENT_STREAM_INSIGHTS: process.env.NEXT_PUBLIC_PRAGMA_AGENT_STREAM_INSIGHTS,
} as const;

const getEnv = <Name extends keyof typeof env>(name: Name): string | undefined => {
  const value = env[name];
  return value && value.length > 0 ? value : undefined;
};


export const MONAD_CHAIN_ID = Number.parseInt(
  getEnv("NEXT_PUBLIC_MONAD_CHAIN_ID") ?? "143",
  10,
);

export const MONAD_BLOCK_EXPLORER_URL =
  getEnv("NEXT_PUBLIC_MONAD_BLOCK_EXPLORER_URL") ?? "https://monadexplorer.com";

export const MONAD_RPC_URL =
  getEnv("NEXT_PUBLIC_MONAD_RPC_URL") ?? "https://rpc.monad.xyz";
export const MONAD_EXECUTION_RPC_URL =
  getEnv("NEXT_PUBLIC_MONAD_EXECUTION_RPC_URL") ??
  MONAD_RPC_URL;
export const MONAD_READ_RPC_URL =
  getEnv("NEXT_PUBLIC_MONAD_ENVIO_READ_RPC_URL") ?? "/api/rpc";
// Removed: MONAD_HYPERSYNC_URL (unused - no code references)

// Removed: ENVIO_TOKEN_API (server-only, use in API routes only)

// Pimlico - Use proxy endpoints (API key stored server-side)
export const PIMLICO_BUNDLER_URL = getEnv("NEXT_PUBLIC_PIMLICO_BUNDLER_URL") ?? "/api/pimlico";
export const PIMLICO_PAYMASTER_URL = getEnv("NEXT_PUBLIC_PIMLICO_PAYMASTER_URL") ?? "/api/pimlico";
export const PIMLICO_SPONSORSHIP_POLICY_ID = getEnv("NEXT_PUBLIC_PIMLICO_SPONSORSHIP_POLICY_ID");

export const WEB3AUTH_CLIENT_ID = getEnv("NEXT_PUBLIC_WEB3_AUTH_ID");
export const WEB3AUTH_NETWORK =
  getEnv("NEXT_PUBLIC_WEB3_AUTH_NETWORK") ?? "sapphire_mainnet";

export const MONORAIL_PATHFINDER_URL =
  getEnv("NEXT_PUBLIC_MONORAIL_PATHFINDER_URL") ?? "https://pathfinder.monorail.xyz/v4";
export const MONORAIL_DATA_API_URL =
  getEnv("NEXT_PUBLIC_MONORAIL_DATA_API_URL") ?? "https://api.monorail.xyz/v2";
// Note: Monorail uses App ID only - no API key required
export const MONORAIL_APP_ID = getEnv("NEXT_PUBLIC_MONORAIL_APP_ID") ?? "";
export const MONORAIL_AGGREGATOR_ADDRESS =
  getEnv("NEXT_PUBLIC_MONORAIL_AGGREGATOR_ADDRESS") ?? "0xA68A7F0601effDc65C64d9C47cA1b18D96B4352c";

export const MONAD_NATIVE_TOKEN_ADDRESS =
  getEnv("NEXT_PUBLIC_MONAD_NATIVE_TOKEN_ADDRESS") ?? "0x0000000000000000000000000000000000000000";
export const MONAD_NATIVE_TOKEN_SYMBOL =
  getEnv("NEXT_PUBLIC_MONAD_NATIVE_TOKEN_SYMBOL") ?? "MON";
export const MONAD_WRAPPED_TOKEN_SYMBOL =
  getEnv("NEXT_PUBLIC_MONAD_WRAPPED_TOKEN_SYMBOL") ?? "WMON";
export const MONAD_WMON_ADDRESS =
  getEnv("NEXT_PUBLIC_MONAD_WMON_ADDRESS") ?? "0x3bd359c1119da7da1d913d1c4d2b7c461115433a";

export const APRIORI_ADDRESS =
  getEnv("NEXT_PUBLIC_APRIORI_ADDRESS") ?? "0x0c65a0bc65a5d819235b71f554d210d3f80e0852";

export const PRAGMA_IDENTITY_PROVIDER =
  (getEnv("NEXT_PUBLIC_PRAGMA_IDENTITY_PROVIDER") ?? "web3auth").toLowerCase();

// Removed: PRIVY_APP_ID (unused)
// Removed: PRIVY_APP_SECRET (unused secret)
// Removed: PRAGMA_ADMIN_TEST_PK (critical secret - use server-only env var in API routes)
// Removed: OPENAI_API_KEY (server-only secret - use in proxy routes only)
// Removed: PRAGMA_DISABLE_HYPERSYNC (unused - no code references)

export const PRAGMA_AGENT_STREAM_INSIGHTS =
  getEnv("NEXT_PUBLIC_PRAGMA_AGENT_STREAM_INSIGHTS") !== "0";
