const env = {
  NEXT_PUBLIC_MONAD_CHAIN_ID: process.env.NEXT_PUBLIC_MONAD_CHAIN_ID,
  NEXT_PUBLIC_MONAD_RPC_URL: process.env.NEXT_PUBLIC_MONAD_RPC_URL,
  NEXT_PUBLIC_MONAD_EXECUTION_RPC_URL: process.env.NEXT_PUBLIC_MONAD_EXECUTION_RPC_URL,
  NEXT_PUBLIC_MONAD_ENVIO_READ_RPC_URL: process.env.NEXT_PUBLIC_MONAD_ENVIO_READ_RPC_URL,
  NEXT_PUBLIC_MONAD_HYPERSYNC_URL: process.env.NEXT_PUBLIC_MONAD_HYPERSYNC_URL,
  NEXT_PUBLIC_ENVIO_TOKEN_API: process.env.NEXT_PUBLIC_ENVIO_TOKEN_API,
  NEXT_PUBLIC_PIMLICO_API_KEY: process.env.NEXT_PUBLIC_PIMLICO_API_KEY,
  NEXT_PUBLIC_PIMLICO_CHAIN: process.env.NEXT_PUBLIC_PIMLICO_CHAIN,
  NEXT_PUBLIC_PIMLICO_BUNDLER_URL: process.env.NEXT_PUBLIC_PIMLICO_BUNDLER_URL,
  NEXT_PUBLIC_PIMLICO_PAYMASTER_URL: process.env.NEXT_PUBLIC_PIMLICO_PAYMASTER_URL,
  NEXT_PUBLIC_PIMLICO_SPONSORSHIP_POLICY_ID: process.env.NEXT_PUBLIC_PIMLICO_SPONSORSHIP_POLICY_ID,
  NEXT_PUBLIC_WEB3_AUTH_ID: process.env.NEXT_PUBLIC_WEB3_AUTH_ID,
  NEXT_PUBLIC_WEB3_AUTH_NETWORK: process.env.NEXT_PUBLIC_WEB3_AUTH_NETWORK,
  NEXT_PUBLIC_MONORAIL_PATHFINDER_URL: process.env.NEXT_PUBLIC_MONORAIL_PATHFINDER_URL,
  NEXT_PUBLIC_MONORAIL_DATA_API_URL: process.env.NEXT_PUBLIC_MONORAIL_DATA_API_URL,
  NEXT_PUBLIC_MONORAIL_API_KEY: process.env.NEXT_PUBLIC_MONORAIL_API_KEY,
  NEXT_PUBLIC_MONORAIL_APP_ID: process.env.NEXT_PUBLIC_MONORAIL_APP_ID,
  NEXT_PUBLIC_MONORAIL_AGGREGATOR_ADDRESS: process.env.NEXT_PUBLIC_MONORAIL_AGGREGATOR_ADDRESS,
  NEXT_PUBLIC_MONAD_NATIVE_TOKEN_ADDRESS: process.env.NEXT_PUBLIC_MONAD_NATIVE_TOKEN_ADDRESS,
  NEXT_PUBLIC_MONAD_NATIVE_TOKEN_SYMBOL: process.env.NEXT_PUBLIC_MONAD_NATIVE_TOKEN_SYMBOL,
  NEXT_PUBLIC_MONAD_WRAPPED_TOKEN_SYMBOL: process.env.NEXT_PUBLIC_MONAD_WRAPPED_TOKEN_SYMBOL,
  NEXT_PUBLIC_MONAD_WMON_ADDRESS: process.env.NEXT_PUBLIC_MONAD_WMON_ADDRESS,
  NEXT_PUBLIC_PRAGMA_IDENTITY_PROVIDER: process.env.NEXT_PUBLIC_PRAGMA_IDENTITY_PROVIDER,
  NEXT_PUBLIC_PRIVY_ID: process.env.NEXT_PUBLIC_PRIVY_ID,
  NEXT_PUBLIC_PRIVY_SECRET: process.env.NEXT_PUBLIC_PRIVY_SECRET,
  NEXT_PUBLIC_PRAGMA_ADMIN_TEST_PK: process.env.NEXT_PUBLIC_PRAGMA_ADMIN_TEST_PK,
  NEXT_PUBLIC_OPENAI_API_KEY: process.env.NEXT_PUBLIC_OPENAI_API_KEY,
  NEXT_PUBLIC_PRAGMA_DISABLE_HYPERSYNC: process.env.NEXT_PUBLIC_PRAGMA_DISABLE_HYPERSYNC,
  NEXT_PUBLIC_PRAGMA_AGENT_STREAM_INSIGHTS: process.env.NEXT_PUBLIC_PRAGMA_AGENT_STREAM_INSIGHTS,
} as const;

const getEnv = <Name extends keyof typeof env>(name: Name): string | undefined => {
  const value = env[name];
  return value && value.length > 0 ? value : undefined;
};


export const MONAD_CHAIN_ID = Number.parseInt(
  getEnv("NEXT_PUBLIC_MONAD_CHAIN_ID") ?? "10143",
  10,
);

export const MONAD_RPC_URL =
  getEnv("NEXT_PUBLIC_MONAD_RPC_URL") ?? "https://testnet-rpc.monad.xyz";
export const MONAD_EXECUTION_RPC_URL =
  getEnv("NEXT_PUBLIC_MONAD_EXECUTION_RPC_URL") ??
  MONAD_RPC_URL;
export const MONAD_READ_RPC_URL =
  getEnv("NEXT_PUBLIC_MONAD_ENVIO_READ_RPC_URL") ?? "https://monad-testnet.rpc.hypersync.xyz";
export const MONAD_HYPERSYNC_URL =
  getEnv("NEXT_PUBLIC_MONAD_HYPERSYNC_URL") ?? "https://monad-testnet.hypersync.xyz";
export const ENVIO_TOKEN_API = getEnv("NEXT_PUBLIC_ENVIO_TOKEN_API");

const PIMLICO_API_KEY = getEnv("NEXT_PUBLIC_PIMLICO_API_KEY");
const PIMLICO_CHAIN = getEnv("NEXT_PUBLIC_PIMLICO_CHAIN") ?? "monad-testnet";
const buildPimlicoUrl = (override?: string) => {
  if (override) return override;
  if (!PIMLICO_API_KEY) return "";
  return `https://api.pimlico.io/v2/${PIMLICO_CHAIN}/rpc?apikey=${PIMLICO_API_KEY}`;
};

export const PIMLICO_BUNDLER_URL = buildPimlicoUrl(getEnv("NEXT_PUBLIC_PIMLICO_BUNDLER_URL"));
export const PIMLICO_PAYMASTER_URL = buildPimlicoUrl(getEnv("NEXT_PUBLIC_PIMLICO_PAYMASTER_URL"));
export const PIMLICO_SPONSORSHIP_POLICY_ID = getEnv("NEXT_PUBLIC_PIMLICO_SPONSORSHIP_POLICY_ID");

export const WEB3AUTH_CLIENT_ID = getEnv("NEXT_PUBLIC_WEB3_AUTH_ID");
export const WEB3AUTH_NETWORK =
  getEnv("NEXT_PUBLIC_WEB3_AUTH_NETWORK") ?? "sapphire_devnet";

export const MONORAIL_PATHFINDER_URL =
  getEnv("NEXT_PUBLIC_MONORAIL_PATHFINDER_URL") ?? "https://testnet-pathfinder.monorail.xyz/v4";
export const MONORAIL_DATA_API_URL =
  getEnv("NEXT_PUBLIC_MONORAIL_DATA_API_URL") ?? "https://testnet-api.monorail.xyz/v1";
export const MONORAIL_API_KEY =
  getEnv("NEXT_PUBLIC_MONORAIL_API_KEY") ?? getEnv("NEXT_PUBLIC_ENVIO_TOKEN_API");
export const MONORAIL_APP_ID = getEnv("NEXT_PUBLIC_MONORAIL_APP_ID") ?? "";
export const MONORAIL_AGGREGATOR_ADDRESS =
  getEnv("NEXT_PUBLIC_MONORAIL_AGGREGATOR_ADDRESS") ?? "0x525B929fCd6a64AfF834f4eeCc6E860486cED700";

export const MONAD_NATIVE_TOKEN_ADDRESS =
  getEnv("NEXT_PUBLIC_MONAD_NATIVE_TOKEN_ADDRESS") ?? "0x0000000000000000000000000000000000000000";
export const MONAD_NATIVE_TOKEN_SYMBOL =
  getEnv("NEXT_PUBLIC_MONAD_NATIVE_TOKEN_SYMBOL") ?? "MON";
export const MONAD_WRAPPED_TOKEN_SYMBOL =
  getEnv("NEXT_PUBLIC_MONAD_WRAPPED_TOKEN_SYMBOL") ?? "WMON";
export const MONAD_WMON_ADDRESS =
  getEnv("NEXT_PUBLIC_MONAD_WMON_ADDRESS") ?? "0x760afe86e5de5fa0ee542fc7b7b713e1c5425701";

export const PRAGMA_IDENTITY_PROVIDER =
  (getEnv("NEXT_PUBLIC_PRAGMA_IDENTITY_PROVIDER") ?? "web3auth").toLowerCase();
export const PRIVY_APP_ID = getEnv("NEXT_PUBLIC_PRIVY_ID");
export const PRIVY_APP_SECRET = getEnv("NEXT_PUBLIC_PRIVY_SECRET");
export const PRAGMA_ADMIN_TEST_PK = getEnv("NEXT_PUBLIC_PRAGMA_ADMIN_TEST_PK");

export const OPENAI_API_KEY = getEnv("NEXT_PUBLIC_OPENAI_API_KEY");
export const PRAGMA_DISABLE_HYPERSYNC = getEnv("NEXT_PUBLIC_PRAGMA_DISABLE_HYPERSYNC") === "1";
export const PRAGMA_AGENT_STREAM_INSIGHTS =
  getEnv("NEXT_PUBLIC_PRAGMA_AGENT_STREAM_INSIGHTS") !== "0";
